### ISSUE TITLE
Many stubs for CBMC proofs are no longer necessary

### ISSUE THREAD

**Issue by feliperodri** [awslabs/aws-c-common#1001]
Many CBMC proofs use stubs for standard C functions (e.g., `memcpy`) that are no longer necessary. By removing these stubs, many proofs could go from bounded to unbounded (e.g., proofs from `aws_byte_buf` module). This no longer makes the proofs stronger, but also could improve performance in CI. We should perform a clean up of these proofs.

**Comment by jmklix** [comment]
Can you make a PR with the changes you're suggesting?
