### ISSUE TITLE
delete tag 08.14

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-c-common#1025]
### Describe the bug

I think the tag 
35a8c659d97cd29085aaa0c6bbb7b80fe88b10fe	refs/tags/v08.14
is wrong - and does confuse our auto version upgrade.

### Expected Behavior

should be deleted.

### Current Behavior

exists

### Reproduction Steps

git clone https://github.com/awslabs/aws-c-common.git
cd aws-c-commmon
git ls-remote

### aws-c-common version used

latest

### Compiler and version used

dont care

### Operating System and version

dont care

**Comment by graebm** [comment]
dangit, the tag is back.
You previously reported this a few weeks back and I deleted it on the server:
https://github.com/awslabs/aws-c-common/issues/1011

It must have gotten pushed back from someone's local copy.

I deleted it again.

I'll look into ways to prevent the tag from getting pushed back again...
