### ISSUE TITLE
Too many threads opened in thread pools on large systems (e.g.  u-12tb1.112xlarge)

### ISSUE THREAD

**Issue by arieleiz** [awslabs/aws-c-common#1039]
### Describe the bug

In the current implementation, sys_info.c::aws_system_info_processor_count() is used to determine the parallelization factor for thread pools. On POSIX systems, the API uses `sysconf(_SC_NPROCESSORS_ONLN)`.

On large systems, such as the u-12tb1.112xlarge instance type, the SDK initiates thread pools with up to 448 threads. This high thread count can potentially lead to S3 operations returning "503 Slow Down" errors due to the high load on a bucket.

The idle cost of these threads is also large when multiple processes use the SDK in parallel, reaching hundreds of thousands of threads on our systems, incurring an idle cost of several cores.

Attached is a pull request to resolve the issue: https://github.com/awslabs/aws-c-common/pull/1038

### Expected Behavior

AWS C SDK should have absolute "safe" limits for system resources and not only relative limits based on system resources.

### Current Behavior

The SDK employs `sysconf(_SC_NPROCESSORS_ONLN)`, which creates thread pools with 448 threads.

### Reproduction Steps

Uee the SDK on a u-12tb1.112xlarge instance.

### Possible Solution

https://github.com/awslabs/aws-c-common/pull/1038

### aws-c-common version used

all

### Compiler and version used

all

### Operating System and version

Linux, all versions

**Comment by waahm7** [comment]
Hi,

Thank you for creating the issue and the pull request. However, overriding the process count using an environment variable doesn't seem like the correct solution. This should be handled at the S3 level. 
> This high thread count can potentially lead to S3 operations returning "503 Slow Down" errors due to the high load on a bucket.

Are you facing this error? If yes, the S3 client has a [max_active_connection_override](https://github.com/awslabs/aws-c-s3/blob/main/include/aws/s3/s3_client.h#L239C32-L240C46), which can be used to limit the active connections. You can also try lowering the [target throughput](https://github.com/awslabs/aws-c-s3/blob/main/include/aws/s3/s3_client.h#L279). Could you please let me know how you are utilizing the S3 client? Are you using it through some SDK?

> The idle cost of these threads is also large when multiple processes use the SDK in parallel, reaching hundreds of thousands of threads on our systems, incurring an idle cost of several cores.

These threads are not active and should not incur much cost. The maximum threads are configurable in the [EventLoopGroup](https://github.com/awslabs/aws-c-io/blob/main/source/event_loop.c#L202), which is passed to the S3 client through the [ClientBootStrap](https://github.com/awslabs/aws-c-s3/blob/main/include/aws/s3/s3_client.h#L246). You could try configuring these.

If that doesn't resolve the issue, please create an issue with details of your use case in aws-c-s3 or the SDK.
