### ISSUE TITLE
MIT license should be included in extra licenses file

### ISSUE THREAD

**Issue by bkmgit** [awslabs/aws-c-common#1060]
### Describe the bug

The [cJSON header](https://github.com/DaveGamble/cJSON) from https://github.com/DaveGamble/cJSON is available under MIT license, and so should also be listed in the
[THIRD-PARTY-LICENSE.txt](https://github.com/awslabs/aws-c-common/blob/main/THIRD-PARTY-LICENSES.txt) file

### Expected Behavior

THIRD-PARTY-LICENSES.txt should contain all third party license

### Current Behavior

THIRD-PARTY-LICENSE.txt contains only one license, BSD-3-Clause

### Reproduction Steps

Examine the file https://github.com/awslabs/aws-c-common/blob/main/THIRD-PARTY-LICENSES.txt

### Possible Solution

Update the file https://github.com/awslabs/aws-c-common/blob/main/THIRD-PARTY-LICENSES.txt

### aws-c-common version used

0.9.3

### Compiler and version used

gcc 15

### Operating System and version

Fedora 40 (rawhide)

**Comment by yasminetalby** [comment]
Hello @bkmgit ,

Thank you very much for your submission. You are right cJSON header from DaveGamble/cJSON used [here](https://github.com/awslabs/aws-c-common/blob/main/source/external/cJSON.c) is under the MIT License ([reference to their LICENSE file](https://github.com/DaveGamble/cJSON/blob/master/LICENSE). 
We do currently include their license at the top of our cJSON.c file.

I am not sure why it is not referred to in the THIRD-PARTY-LICENSE.txt . 

I'll submit a fix for it.

Thank you very much for reporting this. We really appreciate your time and feedback!

Best regards,

Yasmine
