### ISSUE TITLE
Consider enabling `-fvisibility=hidden` when building a static library.

### ISSUE THREAD

**Issue by teo-tsirpanis** [awslabs/aws-c-common#1142]
### Describe the feature

When building `aws-c-common` (and the other AWS C libraries), we pass `-fvisibility=hidden`, but only when building a shared library (since #516). I am proposing to pass it always.

### Use Case

Compiling with `-fvisibility=hidden` makes sense in static libraries too (see [related CMake policy](https://cmake.org/cmake/help/latest/policy/CMP0063.html)). There has been [an issue](https://github.com/apache/arrow/issues/42154) where the interaction between two Python wheels with their own statically linked copy of the AWS SDK resulted in unexplained failures, because both AWS SDKs exported private symbols, which was fixed by forcing the AWS libraries in one of the wheels to compile with `-fvisiblity=hidden`.

The AWS SDK is already [going to always enable](https://github.com/aws/aws-sdk-cpp/blob/878d0c1ca7a0f068dc03e90fde600e5424bf11d9/CMakeLists.txt#L372-L374) `-fvisiblity=hidden` and so does s2n for non-testing builds. This issue tracks doing the same for the AWS C libraries.

### Proposed Solution

Revert to the behavior before #516, or follow s2n's example and pass `-fvisibility=hidden` always unless we have enabled testing and are building a shared library.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
Thanks @teo-tsirpanis for this suggestion. This is something that we would like to do, but I don't have a timeline for when this will get implemented

**Comment by waahm7** [comment]
Fixed in https://github.com/awslabs/aws-c-common/releases/tag/v0.10.0.
