### ISSUE TITLE
Fails to detect lack of NUMA

### ISSUE THREAD

**Issue by jpg0** [awslabs/aws-c-common#1162]
### Describe the bug

System info tests fail on my machine due to attempt at using NUMA and finding an empty cpu group.

### Expected Behavior

Tests pass, NUMA is detected as unavailable.

### Current Behavior

common.c correctly loads `libnuma`, even references `g_numa_available_ptr`, however never actually checks to see it NUMA is available (it is not on my system, and returns -1). During the system info tests a single group is detected, however all cpus are in group `-1` as returned by libnuma. This fails the test. Instead numa should be entirely disabled if it's unavailable. 

### Reproduction Steps

compile and run tests. 

### Possible Solution

Numa should be entirely disabled if it's unavailable. Note that if I remove libnuma.so.1, the tests pass as numa is correctly disabled.

### Additional Information/Context

This is running on an Odroid N2+, using Ubuntu 22.04.

Amlogic S922X Processor
Quad-core Cortex-A73 and Dual-core Cortex-A53

### aws-c-common version used

HEAD

### Compiler and version used

gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

### Operating System and version

Ubuntu 22.04 aarch64

**Comment by jpg0** [comment]
Just tested and it all works now, so this branch is good. Thanks!

**Comment by TingDaoK** [comment]
Thanks for confirming. The PR with the fix has been merged. Let us know if you have any further question!
