### ISSUE TITLE
xml_parser does not support empty tags

### ISSUE THREAD

**Issue by rvansa** [awslabs/aws-c-common#1165]
### Describe the bug

I am trying to connect using `aws-c-s3` to a localstack instance. On listing objects in a bucket localstack replies with
```
<?xml version='1.0' encoding='utf-8'?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01\">
  <IsTruncated>false</IsTruncated>
  <Name>foo</Name>
  <Prefix />
  <MaxKeys>1000</MaxKeys>
  <EncodingType>url</EncodingType>
  <KeyCount>1</KeyCount>
  <Contents> (redacted) </Contents>
</ListBucketResult>
```
but xml_parser is unable to parse empty tag `<Prefix />`: it ignores that it is an empty tag and looks for `</Prefix>`, failing to parse the document.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Valid XML is parsed.

### Current Behavior

Parser logs `XML document is invalid.` and returns error.

### Reproduction Steps

Try to parse
```
<?xml version='1.0' encoding='utf-8'?>
<foo><bar /></foo>
```

### aws-c-common version used

v0.9.27

### Compiler and version used

GCC 11.2

### Operating System and version

Linux

**Comment by jmklix** [comment]
Thanks for finding this bug. We have a PR that should fix this: https://github.com/awslabs/aws-c-common/pull/1168
