### ISSUE TITLE
Packaging Challenges

### ISSUE THREAD

**Issue by psalvaggio** [awslabs/aws-c-common#213]
Hello, it looks like the AWS C++ SDK depends on this library, so I'm trying to package this library so I can continue to package that library. Currently, this library has a couple challenges to packaging.

1. When building shared libraries, only a .so file is output (normally there's symlinks with the API/ABI versions). CMake let's you do this with `set_target_properties()` with `VERSION` and `SOVERSION`. Normally the `.so` link goes in the development package, while the other two go into the runtime package.
2. On Fedora, the libraries are going to /usr/lib instead of /usr/lib64. This can be solved by using the GNUInstallDirs package in CMake.
3. This file: /usr/include/aws/testing/aws_test_harness.h is getting installed when perhaps it doesn't need to be?
4. The CMake config install is a little funky. Currently it is installing the files listed below. Would it be possible to dump everything into a `$LIBDIR/cmake/aws-c-common` directory so there's no risk of conflicts with other packages? Are all of these files required or just the two config files?
```
-- Installing: /builddir/build/BUILDROOT/aws-c-common-0.1-1.x86_64/usr/lib/aws-c-common/cmake/aws-c-common-config.cmake
-- Installing: /builddir/build/BUILDROOT/aws-c-common-0.1-1.x86_64/usr/lib/aws-c-common/cmake/aws-c-common-config-release.cmake
-- Installing: /builddir/build/BUILDROOT/aws-c-common-0.1-1.x86_64/usr/lib/cmake/AwsCFlags.cmake
-- Installing: /builddir/build/BUILDROOT/aws-c-common-0.1-1.x86_64/usr/lib/cmake/AwsTestHarness.cmake
-- Installing: /builddir/build/BUILDROOT/aws-c-common-0.1-1.x86_64/usr/lib/cmake/LibFuzzer.cmake
-- Installing: /builddir/build/BUILDROOT/aws-c-common-0.1-1.x86_64/usr/lib/cmake/Sanitizers.cmake
```

I'm really only familiar with packaging RPMs, but I could probably help set up CPack for RPMs if needed.

Thanks,
Phil

**Comment by justinboswell** [comment]
Hi Phil,

1. I've got a fix for this, I believe. I will be testing it and it'll be in this PR: #214.
2. I'm experimenting with GNUInstallDirs right now
3. The test harness is a dependency of all of our C libraries which consume aws-c-common, so it should be installed
4. I have prefixed the cmake scripts so none of them should conflict. I'm going to chat with the team internally to see if we want to just throw them all in a folder, or if prefixing is sufficient for our expected use cases.

Regarding CPack, if you have experience with that, that would be helpful, we haven't messed with packaging yet.

**Comment by psalvaggio** [comment]
Awesome, I made an initial version of what I think CPack packaging may look like and PR'ed it here:
https://github.com/awslabs/aws-c-common/pull/216

Happy to update it to reflect the changes in 214 if y'all think it's a valuable contribution.

**Comment by justinboswell** [comment]
We'll finish this in #216.
