### ISSUE TITLE
Counting is hard

### ISSUE THREAD

**Issue by cperciva** [awslabs/aws-c-common#229]
The comment here

https://github.com/awslabs/aws-c-common/blob/67262a9a458585400187417d49c39c737507f671/source/encoding.c#L55

says "there's 16 bytes per row" but it looks to me like there's 19 bytes per row in the table which immediately follows the comment.

**Comment by JonathanHenson** [comment]
Ha! There were 16 bytes per row before clang format got a hold of it.

**Comment by JonathanHenson** [comment]
If you care to make it 16 bytes per row AND somehow do it in a way where clang format doesn’t change it, I’d welcome the PR.

**Comment by cperciva** [comment]
I had a feeling it was something like that.  ;-)

I didn't submit a PR since I wasn't sure how you would want this fixed -- I would normally put 16 bytes per row but I don't know if there's a way to do that without having tools break it again.

**Comment by cperciva** [comment]
Google suggests that `/* clang-format off */` and `/* clang-format on */` will work, assuming that clang-format is the only tool you're using for this -- is that something you'd like me to do?

**Comment by JonathanHenson** [comment]
If you’d like to, you could make it 16 bytes and turn clang format off for that block. Then run ./format-check.sh and make sure clang skips it.

**Comment by cperciva** [comment]
PR opened: https://github.com/awslabs/aws-c-common/pull/230

I wasn't able to run format-check.sh because the script is broken (`/bin/bash`, really?) but I ran clang-format manually and it was satisfied.
