### ISSUE TITLE
Integrate remaining aws_string proofs once necessary CBMC enhancements done

### ISSUE THREAD

**Issue by danielsn** [awslabs/aws-c-common#282]
- [ ] aws_string_new_from_c_str
- [ ] aws_string_new_from_array
- [ ] aws_string_new_from_string
- [ ] aws_array_list_comparator_string

**Comment by ColdenCullen** [comment]
What's the status of this? Can it be closed?

**Comment by tautschnig** [comment]
@danielsn ?
