### ISSUE TITLE
Should aws_X_clock_get_ticks() return an error code?

### ISSUE THREAD

**Issue by graebm** [awslabs/aws-c-common#35]
Reading the kernel docs, it doesn't seem like these functions can ever fail the way we're using them.

In code we're writing that calls `aws_X_clock_get_ticks()`, it can be very difficult to handle situations where the clock returned a theoretical error code, so we're not bothering with thorough error handling.

Perhaps the signature should simply be:
`AWS_COMMON_API uint64_t aws_X_clock_get_ticks(void);`

**Comment by JonathanHenson** [comment]
I tend to agree. @bdonlan thoughts?
