### ISSUE TITLE
Usage of `aws_mutex_init()` vs `AWS_MUTEX_INIT`

### ISSUE THREAD

**Issue by graebm** [awslabs/aws-c-common#36]
There are cases in our code of `AWS_MUTEX_INIT` being used to initialize a mutex within a function.

Documentation for [PTHREAD_MUTEX_INITIALIZER](https://linux.die.net/man/3/pthread_mutex_init) says that the macro is intended for use with static variables. Likewise with the [SRWLOCK_INIT](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683483(v=vs.85).aspx) macro on Windows.

However, [libc++'s implementation](http://llvm.org/svn/llvm-project/libcxx/trunk/include/__mutex_base) of `std::mutex` uses the macro in its constructor, and the constructor is `noexcept`.

Googling around, I found [this blog post](https://embeddedartistry.com/blog/2018/1/29/implementing-stdmutex-with-threadx#breaking-with-the-standard-initializing-std-mutex-) about implementing `std::mutex` for embedded systems, and how the author needed to remove the `noexcept` from the constructor because it could throw.

So should we:
1) Only use the macro for statically allocated mutexes?
2) Always use the macro, and simplify our codebase by removing the `aws_mutex_init()` and `aws_mutex_clean_up()` functions.

**Comment by RandyGaul** [comment]
Reading the pthread docs, sounds like the static initializer is only useful for default settings/attributes, and it skips error checking.

Why not just use appropriate initializer functions, and avoid the initializer macro entirely?
