### ISSUE TITLE
build fails on Windows 2008 R2

### ISSUE THREAD

**Issue by Symc-AWS** [awslabs/aws-c-common#401]
While building dependent library aws-c-common , from the link "https://github.com/awslabs/aws-c-common 
  
  
" as instructed (mentioned below) , getting errors like " - Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed", "-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed" , "-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Failed -- Performing Test HAVE_MSVC_CPUIDEX - Failed"

 "Or on windows, cmake -G "Visual Studio 14 2015 Win64" ../aws-c-common" 

-- The C compiler identification is MSVC 19.0.24215.1 -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed -- Performing Test AWS_HAVE_MSVC_MULX -- Performing Test AWS_HAVE_MSVC_MULX - Success -- Performing Test AWS_HAVE_GCC_INLINE_ASM -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Failed -- Performing Test AWS_HAVE_EXECINFO -- Performing Test AWS_HAVE_EXECINFO - Failed -- Performing Test HAVE_M_AVX2_FLAG -- Performing Test HAVE_M_AVX2_FLAG - Success -- Performing Test HAVE_AVX2_INTRINSICS -- Performing Test HAVE_AVX2_INTRINSICS - Success -- Performing Test HAVE_MM256_EXTRACT_EPI64 -- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed -- Performing Test HAVE_MAY_I_USE -- Performing Test HAVE_MAY_I_USE - Failed -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Failed -- Performing Test HAVE_MSVC_CPUIDEX -- Performing Test HAVE_MSVC_CPUIDEX - Success -- Looking for stdint.h -- Looking for stdint.h - found -- Looking for stdbool.h -- Looking for stdbool.h - found -- Performing Test HAS_WGNU -- Performing Test HAS_WGNU - Failed -- Performing Test HAVE_SYSCONF -- Performing Test HAVE_SYSCONF - Failed -- Building SIMD base64 decoder -- Packaging is only supported on Linux -- Configuring done -- Generating done --

**Comment by Symc-AWS** [comment]
On behalf of Symantec your customer. Already case is opened from Symantec, but resolution is yet not recieved

**Comment by bretambrose** [comment]
This is feature test output.  Do you have actual build errors?

**Comment by ColdenCullen** [comment]
Closing due to no response in the last 7 days.
