### ISSUE TITLE
Undefined behavior in byte_cursor_limit_tests

### ISSUE THREAD

**Issue by jkuszmaul** [awslabs/aws-c-common#466]
At https://github.com/awslabs/aws-c-common/blob/c27fcc8da20835d57628997d3b653f83269ac569/tests/cursor_test.c#L233
in `byte_cursor_limit_tests`, `aws_byte_buf_write` is called _after_ `aws_byte_buf_clean_up(&buffer)` (which I assume is intentional). This results in a call to `memcpy` with `NULL` pointer and a length of zero. This appears to be undefined behavior (see https://en.cppreference.com/w/c/string/byte/memcpy), and results in the test failing if I run it under clang's ubsan.

**Comment by TingDaoK** [comment]
https://github.com/awslabs/aws-c-common/blame/main/source/byte_buf.c#L1447-L1450
