### ISSUE TITLE
Reliance on overflow behavior in tests

### ISSUE THREAD

**Issue by jkuszmaul** [awslabs/aws-c-common#467]
When I run some of the tests in https://github.com/awslabs/aws-c-common/blob/master/tests/math_test.c (at tag v0.4.2 (018e74cf55419908ebc0c41ba5721105474e2731)) optimized using clang to compile them, the tests fail due to the overflow behavior being different from expected. Is there something particular relying on the overflow behavior defined by the tests? I can't tell if the failure of the tests is indicating that I should not be using the compiler/flags that I am, or if it just means that the tests are poorly written.

**Comment by jmklix** [comment]
Is this still happening in the latest version? If so can you provide more details about the tests that are failing and the errors that you are seeing?

**Comment by jkuszmaul** [comment]
I do not know, and unfortunately the situation where I observed this was at a company which no longer exists and unfortunately I appear to have failed to document exactly what I was observing 4.5 years ago... I do work with a couple of projects that import the SDK right now, so I may prod at this to see if I can surface any issues here.

**Comment by jmklix** [comment]
I believe this was fixed in a previous release. If you or anyone else is still sees this happening with any of the tests please open a new issue.
