### ISSUE TITLE
[OSX] Hardcoded CoreFoundation path in aws-c-common-targets.cmake

### ISSUE THREAD

**Issue by kszucs** [awslabs/aws-c-common#510]
I don't have Xcode installed locally, only command line tools, so the linker cannot locate CoreFoundation:

```cmake
set_target_properties(AWS::aws-c-common PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "AWS_COMMON_USE_IMPORT_EXPORT"
  INTERFACE_COMPILE_OPTIONS "-pthread"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-pthread;pthread;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework"
)
```

A temporary solution is [overriding it](https://github.com/apache/arrow/pull/5423/files#diff-2420b0c5b6bdad921f1d538f92d64b59R2546).

### What platform/OS are you using?

OSX Mojave

### Which version of the SDK?

Installed by home-brew:

```
aws-sdk-cpp: stable 1.7.180 (bottled), HEAD
AWS SDK for C++
https://github.com/aws/aws-sdk-cpp
/usr/local/Cellar/aws-sdk-cpp/1.7.180 (22,152 files, 426.2MB)
  Poured from bottle on 2019-09-18 at 15:36:12
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/aws-sdk-cpp.rb
```

Original issue: https://github.com/aws/aws-sdk-cpp/issues/1245

**Comment by JonathanHenson** [comment]
Hey quick question, in aws-c-common’s cmake config file, could you add a find_dependency call to CoreFoundation, and see if your consumer re-resolves at link time?

**Comment by kszucs** [comment]
Hey Jonathan, just saw your response. I'll try to check it in the upcoming days.

**Comment by xhochy** [comment]
Make a PR to fix this: https://github.com/awslabs/aws-c-common/pull/700
