### ISSUE TITLE
byte_swap_test fails on big-endian targets

### ISSUE THREAD

**Issue by glaubitz** [awslabs/aws-c-common#556]
The test ```byte_swap_test``` fails on big-endian targets with:

```
[  159s] 201/317 Test #202: byte_swap_test .......................................................***Failed    0.15 sec
[  159s] ***FAILURE*** 43707 != 11189196: ***FAILURE*** aws_ntoh24(z24) != ans_z [s_byte_swap_test_fn():../tests/byte_order_test.c@#56]
[  159s] ***FAILURE*** byte_swap_test [ [31mFAILED[0m ] [s_aws_run_test_case():../include/aws/testing/aws_test_harness.h@#394]
[  159s]
```

Full log for a run on s390x which is big-endian here: https://build.opensuse.org/package/live_build_log/devel:libraries:c_c++/aws-c-common/openSUSE_Factory_zSystems/s390x

**Comment by bretambrose** [comment]
ntoh24 was removed/refactored around a while back.  Please reopen if there is still a swap/encoding issue on big endian.
