### ISSUE TITLE
Consolidate CRT's thread-local storage

### ISSUE THREAD

**Issue by nchong-at-aws** [awslabs/aws-c-common#565]
Consider adding a thread-local storage system in common that everything else hangs off of so that the CRT's usage is always a single slot.

Current use of thread-local storage:
- `int tl_last_error` in `source/error.c`
- `void *tl_thread_handler_context` in `source/error.c`
- `struct tl_logging_thread_id` in `source/log_formatter.c` (#563)

**Comment by jmklix** [comment]
We appreciate your feedback and contribution. I am closing this issue for now as we are currently focused on higher priority item and will not implement this anytime soon.
