### ISSUE TITLE
find_package(Threads REQUIRED) failed with XBox build

### ISSUE THREAD

**Issue by wps132230** [awslabs/aws-c-common#567]
I am trying to update `aws-sdk-cpp`'s dependencies including `aws-c-common` to its latest version and build it on XBox.

I can build `aws-c-common` without any issue. But when I build `aws-sdk-cpp` and cmake tries to run `aws-c-common-config.cmake`, it encountered errors saying that `find_package` could not find `thread` with the following line: https://github.com/awslabs/aws-c-common/blob/30075fca6079d32054a63f217abe9f0e7bdd0db0/cmake/aws-c-common-config.cmake#L2

And after I commented this line, everything works for me now.

For temporary resolution, I can remove this line after I install `aws-c-common`. But for the long run, what will be a better solution? Shall we put this line in a `if(PLATFORM_CUSTOM)`-`endif()` block?

**Comment by bretambrose** [comment]
The fix for this appears to be merged.
