### ISSUE TITLE
Fix aws_thread and aws_condition_variable header doc

### ISSUE THREAD

**Issue by nchong-at-aws** [awslabs/aws-c-common#580]
1. In `thread.h` the doc for `aws_thread_clean_up` currently reads:

```
/**
 * Cleans up the thread handle. Either detach or join must be called
 * before calling this function.
 */
```

But the function itself detaches the thread (if it is currently running). There is no function to detach a thread and calling `aws_thread_join` before this function makes it a no-op.

In `condition_variable.h`:

2. The docs for `aws_condition_variable_wait`, `aws_condition_variable_wait_pred`, `aws_condition_variable_wait_for`, and `aws_condition_variable_wait_for_pred` should note that the function must be called with the mutex locked by the calling thread otherwise the behavior is undefined.

3. Additionally, the docs for `aws_condition_variable_wait` and `aws_condition_variable_wait_for` should note that spurious wakeups can occur: i.e., the return of the function does not apply anything about the wakeup condition associated with the variable. To avoid this problem the user can use the `_pred` versions of these functions or re-test the condition explicitly.

**Comment by jmklix** [comment]
1. Fixed with this PR: https://github.com/awslabs/aws-c-common/pull/814
2 & 3 will be fixed with this PR: [improve condition_variable documentation](https://github.com/awslabs/aws-c-common/commit/dc1d4be8b02b80db09337951317b74b27170872d)
