### ISSUE TITLE
CMake and "Visual Studio 14 2015 Win64"

### ISSUE THREAD

**Issue by kentbarber** [awslabs/aws-c-common#584]
I can successfully build the aws-sdk-cpp for VS 2017 using "Visual Studio 15 2017 Win64". But when I try to build it for 2015 it has problems with the .deps. So I have been trying to create the project files for aws-c-common manually and run into the same problem. It can't find the compiler "rc.exe". 

Has anyone else been able to create the project files for VS 2015 recently? That is when you have VS 2017 (and 2019 in my case) also installed on your system.

I have a lot of projects that I compile via Jenkins on every VS platform, using CMake, and none of them have any issues at all with using -G "Visual Studio 14 2015 Win64". So I am just wondering if something is incorrect in these dependency projects.

This is what I am calling from within a build folder in aws-sdk-cpp

`cmake ../ -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY="s3;transfer" -DENABLE_TESTING=OFF -DENABLE_RTTI=OFF -DCMAKE_SYSTEM_VERSION=8.1 -Tv140`

----

With the error message being the following...

```
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: 1.7.266
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:7 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:7 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "F:/aws-sdk-cpp/build/.deps/CMakeFiles/CMakeOutput.log".
See also "F:/aws-sdk-cpp/build/.deps/CMakeFiles/CMakeError.log".
CMake Error at CMakeLists.txt:229 (message):
  Failed to configure third-party libraries.

```
-----------------------

And the error in the log file being

`  LINK : fatal error LNK1158: cannot run 'rc.exe' [F:\aws-sdk-cpp\build\.deps\CMakeFiles\3.11.2\CompilerIdCXX\CompilerIdCXX.vcxproj]`

----

I have also, as mentioned,  tried compiling this dependency directly. And did so from a VS2015 x64 Native Tools command prompt after also running the vcvarsall.bat command as follows 

- "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 8.1
- cmake -G "Visual Studio 14 2015 Win64" ../aws-c-common

I then get the same error as above.

`LINK : fatal error LNK1158: cannot run 'rc.exe' [F:\aws-c-common-build\CMakeFiles\3.11.2\CompilerIdC\CompilerIdC.vcxproj]`

But if I simply type "rc.exe" in the command prompt it finds the correct compiler. But CMake does not.

----

May be an error on my part, but interested to know from anyone else if they have been able to compile the latest version under VS 2015. 

Thanks.

**Comment by bretambrose** [comment]
Late follow up here: while the error is getting hit while building common, it seems more likely that the issue may lie in how aws-c-common and the C++ sdk are integrated together.  In particular, aws-c-common builds in CI for vs2015 and 2017, and I personally haven't encountered an issue when building it on a windows system that has both installed simultaneously.  You may get more traction if this issue gets created on the C++ SDK repository (the C++ team and the common runtime team overlap and work closely together) which is the root of how you repro the issue.

**Comment by kentbarber** [comment]
Thanks for the reply. The issue turned out to be a very simple one. I just
needed to update my version of CMake to be the latest available. Then the
project compiled fine.
