### ISSUE TITLE
backtrace / backtrace_symbols on libc-musl enabled systems 

### ISSUE THREAD

**Issue by misl6** [awslabs/aws-c-common#616]
## **Problem:**
`backtrace` and `backtrace_symbols` functions used are unavailable on libc-musl enabled systems.
https://github.com/awslabs/aws-c-common/blob/da1ae9c20e3c6734e68808b2afdb4232f97a7118/source/posix/system_info.c#L250
https://github.com/awslabs/aws-c-common/blob/da1ae9c20e3c6734e68808b2afdb4232f97a7118/source/posix/system_info.c#L254

## **Proposed Solution:**
Add a preprocessor flag that could help handling this case.

Similar to https://github.com/awslabs/s2n/issues/1725

**Comment by justinboswell** [comment]
We already have a feature test for ```execinfo.h``` which emits AWS_HAVE_EXECINFO. Is this not being invoked on your target platform? If so, what is that platform? I tested it on Alpine a few weeks ago.

**Comment by misl6** [comment]
I'm crosscompiling `aws-crt-python` via a `openwrt-18.06` toolchain for a `MIPs 24K CPU`

**Comment by misl6** [comment]
Closing, the issue was present in `s2n`, but not over here. I just need a new pair of glasses.
