### ISSUE TITLE
Math.h does not compile on MSVC

### ISSUE THREAD

**Issue by deejaweej** [awslabs/aws-c-common#717]
There are multiple mismatches between the header declarations and inline definitions on MSVC. See:
https://github.com/awslabs/aws-c-common/blob/master/include/aws/common/math.h#L74
https://github.com/awslabs/aws-c-common/blob/master/include/aws/common/math.msvc.inl#L70

**Comment by TingDaoK** [comment]
it has been fixed https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/math.msvc.inl#L113
