### ISSUE TITLE
Please reopen / adress #700

### ISSUE THREAD

**Issue by xhochy** [awslabs/aws-c-common#728]
PR #700 was closed without comment but is actually an annoying thing for packaging things on macOS. It would be nice to get this fixed upstream (i.e. here) instead of continuously patching it in conda-forge.

**Comment by bretambrose** [comment]
I believe that was closed due to transitioning from master -> main.  If you can resubmit the PR, hopefully someone with a Mac can take a look at it.

**Comment by xhochy** [comment]
Already did this in https://github.com/awslabs/aws-c-common/pull/733

**Comment by bretambrose** [comment]
PR merged
