### ISSUE TITLE
Build error under Clang 11 due to [-Werror,-Wstrict-prototypes]

### ISSUE THREAD

**Issue by ihnorton** [awslabs/aws-c-common#729]
```
src/AwsCCommon/source/posix/system_info.c:136:34: error:
this old-style function definition is not preceded by a prototype [-Werror,-Wstrict-prototypes]
const char *s_get_executable_path() {
```

```
 -- The C compiler identification is Clang 11.0.0
 -- The CXX compiler identification is Clang 11.0.0
```
system: `3.8.6 Darwin/19.6.0 OSX/10.15.7`
sdk: `CMAKE_OSX_SYSROOT=/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk`

Please note that these flags are set [by this library itself](https://github.com/awslabs/aws-c-common/blob/a61f2ea5fbc9ac2eee9fe32f7a3fdbd399d9fbdb/cmake/AwsCFlags.cmake#L51), with - insofar as I can tell - no way to disable them as a library consumer or packager.

**Comment by bretambrose** [comment]
In theory fixed by https://github.com/awslabs/aws-c-common/pull/770 however clang 11 CI is not in place yet.
