### ISSUE TITLE
common/atomics_msvc.inl errors out when built on ARM

### ISSUE THREAD

**Issue by cedral** [awslabs/aws-c-common#753]
I tried to build the vcpkg for arm64-windows and got
```include/aws/common/atomics_msvc.inl(20): fatal error C1189: #error:  Atomics are not currently supported for non-x86 MSVC platforms```
looking in that file it looks like somebody simply hard coded it not to support ARM. Are there any plans to fix this in the near future?
I also got a warning about an unused variable you might want to fix:
```source\arch\arm\msvc\cpuid.c(19): warning C4100: 'feature_name': unreferenced formal parameter```
That latter one is a simple change from
```bool aws_cpu_has_feature(enum aws_cpu_feature_name feature_name)```
to
```bool aws_cpu_has_feature(enum aws_cpu_feature_name)```

**Comment by jmklix** [comment]
What are the steps that you are following to get this error when building on windows?
