### ISSUE TITLE
Undefined Behaviour corner case for aws_byte_cursor_advance

### ISSUE THREAD

**Issue by giltho** [awslabs/aws-c-common#771]
Hello !

In the aws_byte_cursor_advance function, currently [line 1052](https://github.com/awslabs/aws-c-common/blob/44b8caff9690701cf60ec9654cb40278b70d8c7e/source/byte_buf.c#L1051), a UB might occur when the function is call with a cursor with a NULL pointer and a length of 0 (because pointer arithmetics on the null pointer is UB)

This is really a corner case, and it is already avoided by aws_byte_cursor_read. But it's an UB that is left unchecked by CBMC (it is a case of valid_aws_byte_cursor), and the documentation does not say to avoid calling advance with len = 0.

**Comment by bretambrose** [comment]
While this would be a relatively simple fix, it makes me wonder if we need additional proof conditions that could go mid-function to assert not null.

**Comment by TingDaoK** [comment]
Hi, thanks for pointing it out. The issue has been fixed with the latest [commit](https://github.com/awslabs/aws-c-common/pull/802). https://github.com/awslabs/aws-c-common/commit/23d543244db6cefd118e6f792b9bfbd5e23d7451#diff-f82be07fe70129742251fb1d643d42eb0eb1bc86adb50f4cbf950045cbac1ccdR1057
