### ISSUE TITLE
Corner case in aws_byte_cursor_advance_nospec

### ISSUE THREAD

**Issue by lmpick** [awslabs/aws-c-common#78]
The comment on line 239 of byte_buf.h indicates that aws_byte_cursor_advance and aws_byte_cursor_advance_nospec should have the same behavior, but there is a corner case where they do not. The problem here occurs when the cursor argument has cursor->len == SIZE_MAX >> 1. The procedure aws_byte_cursor_advance_nospec then passes cursor->len + 1 as the bound argument to aws_nospec_index (line 256 in byte_buf.h), and since cursor->len + 1 is larger than SIZE_MAX >> 1 in this case, aws_nospec_index returns 0. Here's an example that exhibits the different behavior:

~~~
#include <aws/common/byte_buf.h>
#include <stdio.h>
#include <stdlib.h>

int main (void) {
    // Make cursor
    struct aws_byte_cursor *cursor0 = malloc(sizeof(*cursor0));
    cursor0->len = (SIZE_MAX >> 1);
    // not going to deref pointer, so don't bother allocating
    cursor0->ptr = NULL;

    // Make copy of cursor0
    struct aws_byte_cursor *cursor1 = malloc(sizeof(*cursor1));
    cursor1->len = cursor0->len;
    cursor1->ptr = cursor0->ptr;

    size_t len = cursor0->len;

    struct aws_byte_cursor rv = aws_byte_cursor_advance(cursor0, len);
    struct aws_byte_cursor rv_nospec = aws_byte_cursor_advance_nospec(cursor1, len);

    // Expect the same result from aws_byte_cursor_advance and
    // aws_byte_cursor_advance_nospec, so nothing should be printed.
    if (rv.len != rv_nospec.len) {
        printf("Different outputs.\n"); // Prints.
    }
    free(cursor0);
    free(cursor1);
    return 0;
}
~~~

**Comment by bdonlan** [comment]
For consistency, we should possibly just use the nospec variant for all cursor advances, particularly if we standardize on using cursors for read and buffers for write.

**Comment by bdonlan** [comment]
The kernel only mitigates spectre gadgets within the kernel itself. Spectre gadgets in userspace require userspace mitigation.
