### ISSUE TITLE
Event loop stops working after 21 days

### ISSUE THREAD

**Issue by kankri** [awslabs/aws-c-common#790]
We have several users having our Windows product using aws-crt-cpp stopped working after a while. I found out that the reason is incorrect handling of timestamp values which makes them invalid after ~21 days of uptime.

The problematic code is in [aws_high_res_clock_get_ticks()](https://github.com/awslabs/aws-c-common/blob/be3e4ff77f9f303262f43c186897967699e03a2f/source/windows/clock.c#L50):
```c
int aws_high_res_clock_get_ticks(uint64_t *timestamp) {
    LARGE_INTEGER ticks, frequency;
    /* QPC runs on sub-microsecond precision, convert to nanoseconds */
    if (QueryPerformanceFrequency(&frequency) && QueryPerformanceCounter(&ticks)) {
        *timestamp = aws_timestamp_convert((uint64_t)ticks.QuadPart, AWS_TIMESTAMP_SECS, AWS_TIMESTAMP_MICROS, NULL) /
                     (uint64_t)frequency.QuadPart;

        *timestamp = aws_timestamp_convert(*timestamp, AWS_TIMESTAMP_MICROS, AWS_TIMESTAMP_NANOS, NULL);
        return AWS_OP_SUCCESS;
    }

    return aws_raise_error(AWS_ERROR_CLOCK_FAILURE);
}
```
The problem is the line
```c
        *timestamp = aws_timestamp_convert((uint64_t)ticks.QuadPart, AWS_TIMESTAMP_SECS, AWS_TIMESTAMP_MICROS, NULL) /
                     (uint64_t)frequency.QuadPart;
```
which starts by multiplying `ticks` by 1,000,000. This will saturate uint64_t when `ticks` is > `UINT64_MAX` / 1000000 = 18446744073709. With a typical `frequency` of 10,000,000 this amounts to 21.3 days. The visible effect of this is that the time stops at 1844675407370000 ns and the event loop starts repeating the following message without ever reaching the task's timestamp:

    detected more scheduled tasks with the next occurring at 1844675407370000, using timeout of 1000. 

The problematic behavior stops only by rebooting the computer.

As an example of a correct way to handle the conversion, @EeroKurimo found out that QT5 function [ticksToNanoseconds()](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qelapsedtimer_win.cpp#n68) (LGPL license) seems to handle the same issue in a way which doesn't have the risk of overflow.

**Comment by kankri** [comment]
PR #793 and release [v0.5.7](../releases/tag/v0.5.7) fixed the problem for us (tested successfully on one client).

**Comment by bretambrose** [comment]
Excellent.
