### ISSUE TITLE
Add `--memory-leak-check` to deallocator proofs

### ISSUE THREAD

**Issue by SaswatPadhi** [awslabs/aws-c-common#805]
We should review all of the deallocator harnesses, e.g. `aws_hash_table_clean_up_harness`, and verify that all of the memory is correctly `free`d.

Also see: https://github.com/awslabs/aws-c-common/pull/802#discussion_r635648340 and aws/s2n-tls#2774.

**Comment by jmklix** [comment]
Has this been added with the merged PR?
