### ISSUE TITLE
Test failure: test_memtrace_stacks

### ISSUE THREAD

**Issue by markus289** [awslabs/aws-c-common#817]
Hello,

I am building an RPM for the shared library of aws-c-common on COPR. One test is failing.

```
        Start 253: test_memtrace_stacks
252/380 Test #253: test_memtrace_stacks .................................................***Failed    0.00 sec
***FAILURE*** Expected condition to be true: strstr(log_buffer, "s_alloc_1") || strstr(log_buffer, s_alloc_1_addr) [s_test_memtrace_stacks():/builddir/build/BUILD/aws-c-common-0.6.2/tests/memtrace_test.c@#155]
***FAILURE*** test_memtrace_stacks [ [31mFAILED[0m ] [s_aws_run_test_case():/builddir/build/BUILD/aws-c-common-0.6.2/include/aws/testing/aws_test_harness.h@#454]
```

The [complete build log](https://download.copr.fedorainfracloud.org/results/markus289/aws-sdk-cpp-rpms/fedora-34-x86_64/02295445-aws-c-common/builder-live.log.gz) is currently available on COPR, but will vanish at some point in the future.

I can provide more details, if needed.

**Comment by jmklix** [comment]
Please make sure that you are using the latest version of all of repo's. If you still run into any tests failing please open a new issue
