### ISSUE TITLE
Test failure on musl: sba_metrics

### ISSUE THREAD

**Issue by r-burns** [awslabs/aws-c-common#839]
The newly-added `sba_metrics` test is failing on my x86_64-unknown-linux-musl system.

```
246/380 Test #251: sba_metrics ..........................................................***Failed    0.02 sec
***FAILURE*** 1 != 32: ***FAILURE*** expected_active_size != aws_small_block_allocator_bytes_active(sba) [s_sba_metrics_test():/build/source/tests/alloc_test.c@#277]
***FAILURE*** sba_metrics [ FAILED ] [s_aws_run_test_case():/build/source/include/aws/testing/aws_test_harness.h@#454]
```

Reproducible via `nix-build -A pkgsMusl.aws-c-common` @ https://github.com/nixos/nixpkgs/commit/70988a3f6d7143c04c7480b2c4cb8e3a117da15c

**Comment by pwillis-els** [comment]
I see the same failure on Alpine; skipping the test manually for now

**Comment by jmklix** [comment]
Please make sure that you are using the latest version of all of repo's. If you still run into any tests failing please open a new issue

**Comment by r-burns** [comment]
Retested on v0.9.27 and the issue appears to have been resolved. Will reenable this test in Nixpkgs' packaging.
