### ISSUE TITLE
Question about fine grained module/subject based logging

### ISSUE THREAD

**Issue by disa6302** [awslabs/aws-c-common#849]
I see this comment in here about module based logging level control:
https://github.com/awslabs/aws-c-common/blob/40dd0e986ea8dfdfb00586d2f81d6408d71edda8/include/aws/common/logging.h#L46

Is there a way to achieve this based on log subject? By the looks of it, I see we can create a logger object of type `aws_logger` and use `aws_logger_standard_options` to set log level. If I require fine grained logging based on subject, how do I do it? 

i also see this: https://github.com/awslabs/aws-c-common/blob/40dd0e986ea8dfdfb00586d2f81d6408d71edda8/include/aws/common/logging.h#L146

Does this comment align with what I am looking to do?

**Comment by bretambrose** [comment]
There are not any controls other than level at the moment.  It's a low priority idea given the ability to filter with external tools.  I think building in support for buffering/rolling and other high throughput aids is probably higher priority, but even that is not on anyone's radar.

**Comment by disa6302** [comment]
Got it. Thank you @bretambrose . 

I wanted to confirm before I went ahead and developed subject based log filtering in the higher level application.

Closing this out.
