### ISSUE TITLE
File rotation in logging

### ISSUE THREAD

**Issue by disa6302** [awslabs/aws-c-common#856]
Is there file rotation available in file logger? I see there is a way to set up filename, but I do not see log rotation happening. My understanding is the file logging option in this library writes to a single file. When an application is run for long, we will want to have log rotation to avoid pressuring the memory of embedded devices. Can we have this as a feature item if rotation is not already supported?

**Comment by jmklix** [comment]
What is your use case for this?

I would suggest looking at the log header files to try doing this:
   - https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/log_channel.h
   - https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/log_formatter.h
   - https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/log_writer.h
   - https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/logging.h
