### ISSUE TITLE
GCC ASan compatibility

### ISSUE THREAD

**Issue by jeremy-coulon** [awslabs/aws-c-common#884]
I looks like ASan support in aws-c-common only works for clang.

I have faced this surprising issue when trying to use ASan with gcc: https://github.com/awslabs/aws-c-http/issues/362

The fix is quite easy. Instead of giving a blacklist as a compilation flag (which is not supported by gcc), blacklist the function directly in code.

I found the macro `AWS_SUPPRESS_ASAN` here: https://github.com/awslabs/aws-c-common/blob/main/include/aws/common/macros.h#L78

It doesn't work with gcc. The recommanded way to define this macro is:
```c
#if defined(__clang__) || defined (__GNUC__)
# define AWS_SUPPRESS_ASAN __attribute__((no_sanitize_address))
#else
# define AWS_SUPPRESS_ASAN
#endif
```
See https://github.com/google/sanitizers/wiki/AddressSanitizer#turning-off-instrumentation

Then you can apply this macro to `hashlittle2()` function.

**Comment by DmitriyMusatkin** [comment]
resolved by https://github.com/awslabs/aws-c-common/commit/e86e1b6f4622ff8f09d8219d00d79bf8025deaae
