### ISSUE TITLE
Missing SOVERSION bump

### ISSUE THREAD

**Issue by stewartsmith** [awslabs/aws-c-common#913]
As we are needing to include `aws-c-common` in Amazon Linux in order to package AWS CLI v2, we need to ensure that the SOVERSION is being updated appropriately to avoid nasty build and runtime surprises.

When looking at the diff between v0.6.14 and v0.7.4, I noticed a couple of changes that should have come with an SOVERSION major or minor bump.

It looks like https://github.com/awslabs/aws-c-common/commit/ee859bf31f2d840c25a1b7cb7d4624aa31b77905 should have introduced a minor bump as it added functionality.

The changes in https://github.com/awslabs/aws-c-common/commit/3eb38301aaca6dd454828a006315c706e5ce3bf8#diff-e4e7fa2904589ee122e13b9546e13b80ef35e509aaa26fa8967ef3238d5533c9L119 appear to also indicate an ABI *change*, which would mean a major SOVERSION bump would be needed as well.

Am I misunderstanding these changes and their impact to shared library ABI?

**Comment by jmklix** [comment]
Sorry for the late reply. We have since bumped the version to [v0.9.23](https://github.com/awslabs/aws-c-common/tree/v0.9.23). So I don't think this is a concern anymore. Please let me know if you have any questions about versioning with this sdk
