### ISSUE TITLE
Preprocessor error in SIZE_MAX: missing binary operator before token "0"

### ISSUE THREAD

**Issue by philippbara** [awslabs/aws-c-common#932]
### Description
I run into a preprocessor error in SIZE_MAX while building the V2X framework [Artery](https://github.com/riebl/artery/) against the CPP SDK. The ITS-G5 network stack is provided by [Vanetza](https://github.com/riebl/vanetza). Vanetza defines SIZE_MAX in [asn_system.h](https://github.com/riebl/vanetza/blob/master/vanetza/asn1/support/asn_system.h#L130) as follows: `#define SIZE_MAX   ((~((size_t)0)) >> 1)`. This leads to an error in [math.h:16](https://github.com/awslabs/aws-c-common/blob/bd417541440e2660bbf9ba33565a24abaefe7a9a/include/aws/common/math.h#L16):
![error](https://user-images.githubusercontent.com/37438743/190902258-60a60d59-d1e7-4de8-a305-6bfe74f23d79.jpg)

### Steps to reproduce
The issue can easily be reproduced by defining SIZE_MAX as ((~((size_t)0)) >> 1) instead of a non constant integral like 18446744073709551615UL (taken from stdint.h). 

### Solution
Came across a similar issue in [crypto++](https://github.com/weidai11/cryptopp/issues/864). Redefining SIZE_MAX like [here](https://github.com/weidai11/cryptopp/commit/e8b07b162feb) solved the issue for me.

### System info:
Linux 5.15.0-47-generic 51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gcc 11.2.0
AWS_SDK_VERSION_STRING "1.9.348"

**Comment by DmitriyMusatkin** [comment]
Note: at the time when this issue was opened Artery had a bug in their headers where they always overrode SIZE_MAX with a non-preprocessor friendly value when compiling using cpp compiler. That has been fixed since then and should not be a problem anymore. 

I dont think we should be overriding SIZE_MAX based on non-standard defines. 

Let us know if its still an issue.

**Comment by graebm** [comment]
The C99 standard requires SIZE_MAX be a constant, safe to use in an `#if`.

See: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf
Section 7.18.3: Limits of other integer types
> these macros shall be replaced by a constant expression suitable for use in #if preprocessing directive

This is a bug in whatever library is re-defining SIZE_MAX.
