### ISSUE TITLE
delete empty .gitmodules file

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-c-common#961]
Hi,
that empty .gitmodules file causing an error in our meta-aws autoupgrade (yes, probably a bug)
But still this empty file is not necessary!?

**Comment by graebm** [comment]
deleted in `main` branch
Do you need a new release tag?

**Comment by thomas-roos** [comment]
no, did this upgrade manually for meta-aws because of the error. Next one should go automatically. Thank you!
