### ISSUE TITLE
Invalid _mulx_u32 CMake check

### ISSUE THREAD

**Issue by fweimer-rh** [awslabs/aws-c-common#968]
This build-time check is invalid:

https://github.com/awslabs/aws-c-common/blob/7959065399a86be95073085be381eedfcbe93538/cmake/AwsFeatureTests.cmake#L36..L43

* GCC defines `_mulx_u32` in a header file so the test always fails.
* A build-time test for `_mulx_u32` does not tell us anything about run-time availability.

Found as part of:

* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

**Comment by TingDaoK** [comment]
The issue has been resolved by https://github.com/awslabs/aws-c-common/pull/974
